### ISSUE TITLE
Using guava instead of guava-jdk5 dependency

### ISSUE THREAD

**Issue by mziccard** [google/google-auth-library-java#68]
We now depend on `guava-jdk5:13.0`. In both `google-cloud-java` and `gax-java` we instead depend on standard `guava` (version 19 and 18 respectively).

Is there any reason for depending on `guava-jdk5`? If not excluded (as we do in `google-cloud-java`), this just results in a bunch of duplicated classes in all projects that use standard `guava`. /cc @anthmgoogle @garrettjonesgoogle

**Comment by mziccard** [comment]
This was fixed with #69

**Comment by suvodeep-pyne** [comment]
This is still an issue.
`1.23.0` depends on `guava-jdk5:17.0` and it causes dependency conflicts with dropwizard `1.2.0` which uses the standard guava `com.google.guava:guava:23.1-jre`

Unfortunately, the method Throwables.throwIfUnchecked(e) doesn't exist in `guava-jdk5:17.0` causing failures in tests.

Could you guys please take a look. The Google client library is the recommended way for authenticating with firebase and we don't want to switch to the legacy API because of this problem.

For readers, this will fix the issue if you are using Gradle
```
compile (group: 'com.google.api-client', name: 'google-api-client', version: '1.23.0') {
  // excludes all guava packages including com.google.guava:guava-jdk5:17.0 which gets pulled in
  exclude group: 'com.google.guava'
}
```

**Comment by martinbonnin** [comment]
Same problem here with 

`
    implementation (group: 'com.google.apis', name:'google-api-services-androidpublisher', version:'v2-rev47-1.23.0') {
    implementation (group: 'com.google.cloud', name: 'google-cloud-storage', version: '1.12.0')
`

I had to `exclude group: 'com.google.guava'` as @suvodeep-pyne mentioned

**Comment by arunsankar8** [comment]
@suvodeep-pyne Thanks man, It worked
